services:

  backend:
    build: dev/docker/backend
    restart: unless-stopped
    working_dir: /src
    command:
      - /bin/bash
      - "-euc"
      - |
        exec entr -n -r -d go run -tags dev ./src/go/cli/docker-graph -bind 0.0.0.0:8080 -logStderr debug -logColor always < <(find src/go)
    stop_signal: SIGTERM
    volumes:
      - .:/src:ro
      - backend_cache:/go
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    image: jarredsumner/bun:edge
    restart: unless-stopped
    working_dir: /src
    command:
      - /bin/sh
      - "-euc"
      - |
        bun install;
        bun bun -c bunfig.toml;
        exec bun dev -c bunfig.toml
    volumes:
      - .:/src

  proxy:
    image: caddy:2
    restart: unless-stopped
    command:
      - /bin/sh
      - "-euc"
      - |
        mkdir -m 0700 -p /certs
        wget -q http://traefik.me/fullchain.pem -O /certs/fullchain.pem
        wget -q http://traefik.me/privkey.pem -O /certs/privkey.pem
        exec caddy run --watch --config /etc/caddy/Caddyfile
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
    volumes:
      - ./dev/docker/proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/var/www:ro
      - proxy_data:/data

volumes:
  backend_cache: ~

  proxy_data: ~
